//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.27 at 11:10:33 PM CET 
//


package net.appuntivari.protocollo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="libro" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="autore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="pagine" type="{http://www.w3.org/2001/XMLSchema}short" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "libro"
})
@XmlRootElement(name = "libri")
public class Libri {

    protected List<Libri.Libro> libro;

    /**
     * Gets the value of the libro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Libri.Libro }
     * 
     * 
     */
    public List<Libri.Libro> getLibro() {
        if (libro == null) {
            libro = new ArrayList<Libri.Libro>();
        }
        return this.libro;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="titolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="autore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="pagine" type="{http://www.w3.org/2001/XMLSchema}short" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titolo",
        "autore"
    })
    public static class Libro {

        @XmlElement(required = true)
        protected String titolo;
        @XmlElement(required = true)
        protected String autore;
        @XmlAttribute
        protected Short pagine;

        /**
         * Gets the value of the titolo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitolo() {
            return titolo;
        }

        /**
         * Sets the value of the titolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitolo(String value) {
            this.titolo = value;
        }

        /**
         * Gets the value of the autore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutore() {
            return autore;
        }

        /**
         * Sets the value of the autore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutore(String value) {
            this.autore = value;
        }

        /**
         * Gets the value of the pagine property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getPagine() {
            return pagine;
        }

        /**
         * Sets the value of the pagine property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setPagine(Short value) {
            this.pagine = value;
        }

    }

}
